### ISSUE TITLE
User current location design

### ISSUE THREAD

**Issue by dhs766** [ucladevx/Mappening-Frontend#141]
Create mockup showing a blue dot (like apple maps) that represents user's current location. (blue dot should be in Mappening's blue colour)

**Comment by TrinaKat** [comment]
![image](https://user-images.githubusercontent.com/17267100/36931588-db1487ea-1e6d-11e8-8ce2-5b009ef846fa.png)
Just mentioning that this is what MapBox's default current location indicator looks like

**Comment by dhs766** [comment]
Ooo yeah that's works!

**Comment by TrinaKat** [comment]
User's current location is only enabled on https (which mappening supports) and I don't believe it can be enabled by default. The current location toggle in the top right enables it though.

**Comment by dhs766** [comment]
Oh I see, what do you think of having a pop-up that asks users for permission to use their location? Does the toggle in the top right enable current location regardless of https?

**Comment by TrinaKat** [comment]
"Not all browsers support geolocation, and some users may disable the feature. Geolocation support for modern browsers including Chrome requires sites to be served over HTTPS. If geolocation support is not available, the GeolocateControl will not be visible."
aka geolocation is not possible over http

When you first click on the toggle button, this pops up:
![image](https://user-images.githubusercontent.com/17267100/36931798-9fe66832-1e72-11e8-9075-c70e8a051fb1.png)

**Comment by TrinaKat** [comment]
Documentation here: https://www.mapbox.com/mapbox-gl-js/api/#geolocatecontrol

Example here: https://www.mapbox.com/mapbox-gl-js/example/locate-user/

**Comment by dhs766** [comment]
Okay so just to clarify, our site is currently served on http but we could do https too? Is there a transition process?

**Comment by TrinaKat** [comment]
It supports both right now so [http](http:://www.whatsmappening.io) and [https](https://www.whatsmappening.io)
