### ISSUE TITLE
Upgrade to PWA

### ISSUE THREAD

**Issue by Kimeiga** [ucladevx/Mappening-Frontend#199]
Upgrade Angular 4 application (dora.whatsmappening.io) to a Progressive Web Application.

May require upgrading entire project to Angular 5

**Comment by jsfuentes** [comment]
Angular 5 by Friday

**Comment by Kimeiga** [comment]
![image](https://user-images.githubusercontent.com/20587215/39225010-f254d602-47fe-11e8-8c79-85fc2dc447e1.png)
I think the app is already angular version 5.2
