### ISSUE TITLE
Mobile Map UI Changes

### ISSUE THREAD

**Issue by lucyliao** [ucladevx/Mappening-Frontend#203]
- [x] Remove tags
- [x] Design for filter menu dropdown
- [x] Make screen for expanded event list
- [x] Filler interaction screens for InVision (event selection, day selection, etc.)
- [x] Update InVision (integrate with mobile calendar UI)
- [x] Upload Sketch file to Figma

**Comment by dhs766** [comment]
look great! Also put sketch designs on figma for melissa
