### ISSUE TITLE
Event for the Day

### ISSUE THREAD

**Issue by jsfuentes** [ucladevx/Mappening-Frontend#41]
Lucy: 
Make design for the event switching
we decided button and a text day indication is probably good, change if ya want ill review the design

Hannah: 
Look at [design](https://drive.google.com/a/g.ucla.edu/file/d/15X9GAj6uAL9u-L5s8naBLrDKzXrtZJ68/view?usp=sharing)
Over the date will be today, tomorrow, or in x days
You can't go before today and you can go forever into the future
Work with backend to get an api to call with the date(katrina)
Update the map with the button and api call

**Comment by TrinaKat** [comment]
- [x] add api call for getting all events on a certain date

You can call the api at IP/api/v1/event-date/<date>
<date> should be a parsable date string
