### ISSUE TITLE
Mobile friendly doesn't work on some Iphones

### ISSUE THREAD

**Issue by tanzeelak** [ucladevx/Mappening-Frontend#91]
I think it has to do with handlebars, but idk lol

**Comment by jsfuentes** [comment]
So, I know debugging is a pain, but .it needs to be done. At the least this week, figure out how to even debug this on iphones and what the problem is.
You dont have to fix it yet, but progress should be made.

**Comment by jsfuentes** [comment]
Basically, the events don't load in on mobile sometimes. Happened on my phone once, but it reported to happen on iphones particularly safari.

**Comment by TrinaKat** [comment]
Seems to work for me now, tbd if still true

**Comment by TrinaKat** [comment]
I think it was changing all the lets to vars
