### ISSUE TITLE
Date .000191001

### ISSUE THREAD

**Issue by jsfuentes** [ucladevx/Mappening-Frontend#94]
When you click the day arrow enough times, there is a floating point error caused by continously adding one around 60, just round

**Comment by jsfuentes** [comment]
Could just solve by capping weeks

**Comment by TrinaKat** [comment]
Perhaps implement this: https://github.com/ucladevx/Mappening-Backend/issues/51

- [ ] Some kind of "today/now" button to get back to current day 
- [ ] A "fast forward/backward" button to jump by a week rather than by a day

**Comment by san2heg** [comment]
I'll try to add those features when I'm making the new date button for issue #111
